config/routes.rb
PopulationEstimator::Application.routes.draw do
  match '/countries/:country_id/places/search' => 'places#search', :as => :search
  resources :countries do
    collection do
      get :search
    end
    resources :places
  end

  match '/tiles/landmass/:x/:y/:zoom.png' => 'land_mass_tile#view', :as => :view
  namespace :admin do
    resources :earth_masses_painter
  end

  root :to => 'countries#index'
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :places
  
  scope :with_country_code, { :conditions => [ "country_code IS NOT NULL" ] } 
  
  # override standard country_code search and make this case insensitive
  def self.find_by_country_code(country_code)
    find(:first, :conditions => ["country_code like ?", country_code] )
  end
  
  # find countries which match string
  def self.find_with_string(name_to_match)
    raise Exception, "Name to match is blank" if name_to_match.blank?
    find(:all, :conditions => ["name like ?", "%#{name_to_match}%"])
  end
  
  # use country_code to identify country as opposed to Primary Key, this is used in the map.routes etc.
  def to_param
    country_code
  end
  
  # obtain the range of latitudes and longitudes from the Places within this country
  #
  # *Note on lat/longs*
  # latitudes: go north (higher) to south (lower)
  # longitudes: go east (higher) to west (lower)
  #
  def lat_long_rectangle_of_entire_country
    Place.lat_long_rectangle_with_descendents(self)
  end

  def country_code_blank?
    country_code.blank?
  end
  
  # used for sorting, returns [boolean for country_code being blank, name]
  def country_code_exists_and_country_name
    [(country_code.blank? ? 1 : 0), name]
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.xml
  def index
    @countries = Country.all.sort_by(&:country_code_exists_and_country_name)
    @map_rectangle = Rectangle.new(0,0,0,0) # GMap will just show a world map
    @place = nil
    
    SLogger.info("#{request.url}")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.xml
  def show
    @country = Country.find_by_country_code(params[:id]) unless params[:id].blank?
    return redirect_to :action => "index" if @country.blank? 
    
    @place = @filtered_places = nil

    @places_filter = (params[:search] ? params[:search][:place_name] : nil)
    if (!@places_filter.blank?)
      @filtered_places = @country.places.name_containing_text(@places_filter)
    else
      @children = @country.places.roots
      @ancestors_and_self = [] # we have no ancestors or self as we are showing root
    end
    
    @map_rectangle = @country.lat_long_rectangle_of_entire_country
    
    respond_to do |format|
      format.js { render_html_with_flash :partial => "places/places_list" } 
      format.html
      format.xml { render :xml => @countries }
    end
  end

  # GET /countries/search
  def search
    @search = OpenStruct.new(params[:search])
    @flash_results = false

    if @search.country_name.blank?
      @countries = Country.all.sort_by(&:country_code_exists_and_country_name)
    else
      @countries = Country.find_with_string(@search.country_name).sort_by(&:country_code_exists_and_country_name)
    end

    @map_rectangle = Rectangle.from_outside_of_rectangles(@countries.reject(&:country_code_blank?).map(&:lat_long_rectangle_of_entire_country)) unless @countries.blank?
    @map_rectangle = Rectangle.new(0,0,0,0) if (@countries.blank? || !@map_rectangle.valid?)
    @place = nil

    respond_to do |format|
      format.js { render_html_with_flash :partial => "country_list" } 
      format.html { render :action => "index" }    
      format.xml { render :xml => @countries }
    end
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
  def map_xpath
    "#map"
  end
    
  def zoom_map_out_to_world()
    javascript_tag_with_wait "ZoomMapToWorld('top');"
  end
  
  def zoom_map_to_rect(rect)
    javascript_tag_with_wait "ZoomMapTo ('top', #{rect.north}, #{rect.south}, #{rect.east}, #{rect.west}, #{rect.latitude_centre}, #{rect.longitude_centre});"
  end
  
  private
  
  def javascript_tag_with_wait(javascript)
    wait_until_load = !request.xhr? # if XHR request, we don't need to wait until the page has loaded
    javascript_tag (wait_until_load ? "$(document).ready (function() {" : "") + javascript + (wait_until_load ? "})" : "")
  end
end

app/views/countries/_country_list.html.haml
#results_list
  - if !@countries.blank?
    %ul#country_list
      - @countries.each do |country| 
        %li 
          =link_to("#{country.name} #{country.country_code}, #{country.population.thousands} people, #{country.density_per_sq_km} p/sq/km", country) unless country.country_code.blank?
          ="#{country.name}, population: #{country.population.thousands}, density p/sq/km: #{country.density_per_sq_km}" if country.country_code.blank?
      
    - if (@map_rectangle.south != 0) || (@map_rectangle.latitude_centre != @map_rectangle.south)
      -# place_to_show_on_map = { name: '#{@place.blank? ? '' : @place.name}' }
      = zoom_map_to_rect(@map_rectangle)
    - else
      = zoom_map_out_to_world
  - else
    %p
      No countries found matching those keywords
    = zoom_map_out_to_world

- if @flash_results
  :javascript
    #{ visual_effect :highlight, 'results_list' }

app/views/countries/_google_map.html.haml
- content_for :javascript do
  %script{ :type=>"text/javascript", :src=>"http://www.google.com/jsapi?key=#{maps_api_key}" }
  %script{ :type=>"text/javascript", :src=>"http://maps.google.com/maps/api/js?sensor=false" }

  :javascript
    $(document).ready(function() {
      var map_canvas = $('#map').get(0);
      SetupMap("top", map_canvas);
    });

#map

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= form_for(@country) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </p>
  <p>
    <%= f.label :population %><br />
    <%= f.text_field :population %>
  </p>
  <p>
    <%= f.label :density_per_sq_km %><br />
    <%= f.text_field :density_per_sq_km %>
  </p>
  <p>
    <%= f.label :source_update_date %><br />
    <%= f.date_select :source_update_date %>
  </p>
  <p>
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </p>
  <p>
    <%= f.label :updated_at %><br />
    <%= f.datetime_select :updated_at %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.haml
- search_target = { :action => "search" }

=render :partial => 'countries/google_map'

= form_tag(search_target, :method => "get") do   
  
  %h1 Countries
  = label :search, :country_name, "Filter by" 
  = text_field :search, :country_name
  = submit_tag "Search", :id => "filter_submit", :name => "submit", :class => "search"

#results_list_container
  =render :partial => 'country_list'

- content_for :javascript do
  :javascript
    $(document).ready (function() { 
      $('#filter_submit').css('display','none'); 
      $('#search_country_name').bind("keyup", function() {
        var form = $(this).parents("form");
        $.get(form.attr("action"), form.serialize(), function(html) { 
           $("#results_list_container").html(html); 
         });
      });
    });

app/views/countries/show.html.haml
- search_target = { :controller => 'places', :country_id => @country.country_code, :action => 'search'}

=render :partial => 'countries/google_map'

%ul
  %li
    =link_to("World", countries_path)
    %ul
      %li
        Country: 
        =link_to(name_with_info(@country), :url => { :action => "show", :controller => "countries", :id => @country.country_code }, :update => "results_list_container", :method => :get, :remote => true)

        = form_tag(:url => search_target, :method => "get", :update => 'results_list_container', :remote => true) do
          = label :search, :place_name, "Search for place within country "
          = text_field :search, :place_name
          = submit_tag "Search", :id => "filter_submit", :name => "submit", :class => "search"

        #results_list_container
          =render :partial => 'places/places_list'

/ hide the filter button if user has javascript
- content_for :javascript do
  :javascript
    $(document).ready (function() {
      $('#filter_submit').css('display','none');
      $('#search_place_name').bind("keyup", function() {
        var form = $(this).parents("form");
        $.get(form.attr("action"), form.serialize(), function(html) {
           $("#results_list_container").html(html);
         });
      });
    });